version: 2
updates:
  - package-ecosystem: github-actions
    commit-message:
      prefix: chore
    cooldown:
      default-days: 7
    directories:
      - /
    schedule:
      interval: daily
  - package-ecosystem: gradle
    commit-message:
      prefix: chore
    cooldown:
      default-days: 7
    directories:
      - /
    schedule:
      interval: daily
